### ISSUE TITLE
ServerOutage: Server cant connect to isp

### ISSUE THREAD

**Issue by KTBZay** [KTBZay/putinsoftware#1]
# Error?:
- Server failed to handshake with ISP 

# How will we fix this?:
- [x] Contact ISP and connect them to this git project
- [x] They will send updates threw the comments to what they will do on there end
- [x] Try to fix the issue
- [x] Restart with monitoring
- [x] Close issue from isp 
- [x] Revaluate the code
- [x] Close issue on git

# Bots that are hosted by KTB(KingTrainerBuildup.corps) or PSF(Pop Smoke Family)
**Theses bots will not function as intented. witch means bots may go off at times and may not stay on**

**Comment by DavidB-ES** [comment]
Dear Users,
We are now processing this issue. this may take 10-35 mins.

**Comment by DavidB-ES** [comment]
Dear Users,
We have found why the server has not handshaked, we are sending the reset signal now.

**Comment by KTBZay** [comment]
# Error?:
- Server failed to handshake with ISP 

# How will we fix this?:
- [x] Contact ISP and connect them to this git project
- [x] They will send updates threw the comments to what they will do on there end
- [x] Try to fix the issue
- [x] Restart with monitoring
- [x] Close issue from isp 
- [x] Revaluate the code
- [x] Close issue on git

# Bots that are hosted by KTB(KingTrainerBuildup.corps) or PSF(Pop Smoke Family)
**Theses bots will not function as intented. witch means bots may go off at times and may not stay on**

**Comment by DavidB-ES** [comment]
# Error Fixed on ISP
**_We have fixed the error on our side by sending a package to the server owners email, please wait while the update is released from the Owner._**

### Report Details:
- Report Number: 2106
- Server SN: WwNXuqR
- Server IP: 192.27.221.829:8901 (VPS)

**Comment by KTBZay** [comment]
# Error?:
- Server failed to handshake with ISP 

# How will we fix this?:
- [x] Contact ISP and connect them to this git project
- [x] They will send updates threw the comments to what they will do on there end
- [x] Try to fix the issue
- [x] Restart with monitoring
- [x] Close issue from isp 
- [x] Revaluate the code
- [x] Close issue on git

# Bots that are hosted by KTB(KingTrainerBuildup.corps) or PSF(Pop Smoke Family)
**Theses bots will not function as intented. witch means bots may go off at times and may not stay on**

**Comment by KTBZay** [comment]
### When will this be updated?
I will update the project in a min

**Comment by KTBZay** [comment]
# Error?:
- Server failed to handshake with ISP 

# How will we fix this?:
- [x] Contact ISP and connect them to this git project
- [x] They will send updates threw the comments to what they will do on there end
- [x] Try to fix the issue
- [x] Restart with monitoring
- [x] Close issue from isp 
- [x] Revaluate the code
- [x] Close issue on git

# Bots that are hosted by KTB(KingTrainerBuildup.corps) or PSF(Pop Smoke Family)
**Theses bots will not function as intented. witch means bots may go off at times and may not stay on**

**Comment by KTBZay** [comment]
### All bot will return to normal functions in 1-3 hours.
