### ISSUE TITLE
001-User-Communitcation-Err

### ISSUE THREAD

**Issue by KTBZay** [KTBZay/putinsoftware#2]
#1  is a refrence but is not the issue
# What happened?
- Server can not contact the bots
# How can this be resolved?
- No possible fix at the momment
 # Components infected
 Bots, MusicBots,ModBots

**Comment by DavidB-ES** [comment]
We are looking at the issue at our side... Please let 3-5 hours for a update

**Comment by KTBZay** [comment]
Security Ticket Num: GHSA-p8rr-5r6p-gj58

**Comment by DavidB-ES** [comment]
We have found no issues on our side, we have moved this issue into our semi-closed so we can assist if the error persists or moves our hosted server

**Comment by KTBZay** [comment]
we have released version #1.0.5, i will not fix this
