### ISSUE TITLE
004- Can not find "About.js"

### ISSUE THREAD

**Issue by DavidB-ES** [KTBZay/putinsoftware#3]
### Is this issue virial(ex "Cyber Threat Related", inc)?
 - No
### What had happen
 - While editing code, a developer stumbled a crossed a bug
### When will this be fixed
- This error as came on an holiday date, we ill start working on the issue on 7/14/22-7/24/22.

# Any comments questions and concerns contacts us through comments

**Comment by DavidB-ES** [comment]
# This issue will be transferred over  to ES connections
Our staff members will look over the code efficiently. We will get back to you as soon as possible ref #1  for more details on how to wait or fix this error yourself

**Comment by ES-Bottles** [comment]
# Support has arrived!

- I am looking into the code files and seeing what all is going on.. please give 5-10 min i will respond when my check is done!

### Ways you could fix this issue
 1. Look up videos on how to learn Nodejs/discordjs
 2. find out where the error is
 3. submit your fix to  KTBZay  in format https:/github/user/repository
 
 ### Ways to bypass this error
 1. Reinstall PutinSoftware all together
 2. Make sure  node is installed
 3. Make sure discord.js is installed

**Comment by ES-Bottles** [comment]
# Issue Found
- i have found 2 of 2 issues and resolved them. you can redownload the files and get back to coding

**Comment by ES-Bottles** [comment]
This issue was solved at 6:11:02 PM EST
